# Generated by Django 3.2.15 on 2022-10-18 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_commidity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单id')),
                ('order_pay_methods', models.CharField(max_length=20, unique=True, verbose_name='支付方式')),
                ('order_all_money', models.FloatField(verbose_name='总金额')),
                ('order_all_number', models.IntegerField(verbose_name='总数量')),
                ('order_pay_state', models.BooleanField(verbose_name='支付状态')),
                ('order_create_time', models.DateTimeField(verbose_name='订单创建时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCommodity',
            fields=[
                ('oc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单商品id')),
                ('oc_number', models.IntegerField(verbose_name='商品数量')),
                ('oc_price', models.FloatField(verbose_name='商品价格')),
                ('oc_comment', models.TextField(null=True, verbose_name='评论')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_order.ordermessage', verbose_name='订单id')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditysku', verbose_name='sku_id')),
            ],
        ),
    ]
