# Generated by Django 3.2.15 on 2022-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermessage',
            name='order_pay_methods',
            field=models.CharField(max_length=20, verbose_name='支付方式'),
        ),
    ]
