# Generated by Django 3.2.15 on 2022-10-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_commidity', '0001_initial'),
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='add_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.address', verbose_name='地址id'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='ordercommodity',
            name='add_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.address', verbose_name='地址id'),
        ),
        migrations.AddField(
            model_name='ordercommodity',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_order.ordermessage', verbose_name='订单id'),
        ),
        migrations.AddField(
            model_name='ordercommodity',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditysku', verbose_name='sku_id'),
        ),
    ]
