# Generated by Django 3.2.15 on 2022-10-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_alter_ordermessage_order_pay_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermessage',
            name='order_pay_state',
            field=models.IntegerField(verbose_name='支付状态'),
        ),
    ]
