# Generated by Django 3.2.15 on 2022-10-18 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityKind',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品种类id')),
                ('com_name', models.CharField(max_length=20, unique=True, verbose_name='商品种类名称')),
                ('com_picture', models.ImageField(upload_to='image', verbose_name='商品种类图片')),
            ],
        ),
        migrations.CreateModel(
            name='CommoditySku',
            fields=[
                ('sku_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品skuid')),
                ('sku_name', models.CharField(max_length=20, unique=True, verbose_name='商品sku名称')),
                ('sku_brief_introduction', models.TextField(verbose_name='商品简介')),
                ('sku_price', models.FloatField(verbose_name='商品价格')),
                ('sku_unit', models.CharField(max_length=10, verbose_name='商品单位')),
                ('sku_stock', models.IntegerField(verbose_name='商品库存')),
                ('sku_slaes', models.IntegerField(verbose_name='商品销量')),
                ('sku_state', models.BooleanField(verbose_name='商品状态')),
                ('sku_discount', models.FloatField(verbose_name='折扣')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditykind', verbose_name='种类id')),
            ],
        ),
        migrations.CreateModel(
            name='CommoditySpu',
            fields=[
                ('spu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品spuid')),
                ('spu_name', models.CharField(max_length=20, unique=True, verbose_name='商品spu名称')),
                ('spu_details', models.TextField(verbose_name='详情')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('rev_content', models.TextField(verbose_name='评论')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditysku', verbose_name='sku_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='HomePromotion',
            fields=[
                ('home_pro_id', models.AutoField(primary_key=True, serialize=False, verbose_name='首页促销活动id')),
                ('home_pro_picture', models.ImageField(upload_to='image', verbose_name='图片')),
                ('home_pro_index', models.IntegerField(verbose_name='顺序索引')),
                ('home_pro_url', models.ImageField(upload_to='image', verbose_name='活动url')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditysku', verbose_name='sku_id')),
            ],
        ),
        migrations.CreateModel(
            name='HomeDisplay',
            fields=[
                ('home_dis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='首页分类商品展示id')),
                ('home_dis_identification', models.BooleanField(verbose_name='展示标识')),
                ('home_dis_index', models.IntegerField(verbose_name='索引')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditykind', verbose_name='商品种类id')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditysku', verbose_name='sku_id')),
            ],
        ),
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('home_car_id', models.AutoField(primary_key=True, serialize=False, verbose_name='轮播id')),
                ('home_car_picture', models.ImageField(upload_to='image', verbose_name='轮播图片')),
                ('home_car_index', models.IntegerField(verbose_name='顺序索引')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditysku', verbose_name='sku_id')),
            ],
        ),
        migrations.AddField(
            model_name='commoditysku',
            name='spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commodityspu', verbose_name='spu_id'),
        ),
        migrations.CreateModel(
            name='CommdityPicture',
            fields=[
                ('comm_id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片id')),
                ('comm_picture', models.ImageField(upload_to='image', verbose_name='图片')),
                ('comm_video', models.FileField(null=True, upload_to='viedo', verbose_name='视频')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_commidity.commoditysku', verbose_name='sku_id')),
            ],
        ),
    ]
